// NUR 326-201 — Week 1 question bank
// topics: principles, cellwall, protein, antivirals, hiv
const QUESTION_BANK = [
  // ---------------- Antimicrobial Principles ----------------
  {topic:"principles", q:"A patient reports nausea and vomiting after taking amoxicillin in the past. How should this be classified?", options:["A true drug allergy","An adverse effect, not an allergy","Cross-reactivity","Anaphylaxis"], correct:1, explain:"N/V is an adverse effect. True allergies are rash, hives, angioedema, or anaphylaxis.", torture:false},
  {topic:"principles", q:"Which best describes a bacteriostatic drug?", options:["It kills the organism outright","It only inhibits bacterial growth; the immune system finishes the job","It increases cell wall permeability","It only works on viruses"], correct:1, explain:"Bacteriostatic drugs stop growth/reproduction without necessarily killing the organism.", torture:false},
  {topic:"principles", q:"A nurse should obtain blood cultures using which technique?", options:["One aerobic bottle only, drawn from a central line","Two sets — one aerobic, one anaerobic — from a peripheral stick","A single anaerobic bottle from any line","Cultures aren't needed if the patient already looks septic"], correct:1, explain:"Two bottles (aerobic + anaerobic) via peripheral stick reduce contamination risk versus central line sources.", torture:false},
  {topic:"principles", q:"Which patient population is the exception to 'always get cultures before starting antimicrobials'?", options:["A patient with a mild UTI","A patient with suspected meningitis or severe sepsis","A patient with a skin rash","A pediatric patient with an ear infection"], correct:1, explain:"Critically ill patients, meningitis, and severe sepsis may need empiric therapy started before culture results return.", torture:false},
  {topic:"principles", q:"What do the letters ESKAPE represent in antimicrobial resistance?", options:["A mnemonic for antibiotic dosing intervals","The six classic multidrug-resistant organisms","A category of beta-lactam antibiotics","The stages of bacterial cell death"], correct:1, explain:"Enterococcus faecium, Staph aureus, Klebsiella pneumoniae, Acinetobacter baumannii, Pseudomonas aeruginosa, Enterobacter spp.", torture:false},
  {topic:"principles", q:"A patient had anaphylaxis to penicillin in the past. What is the safest approach to a similar beta-lactam?", options:["Cephalosporins are always safe to give","Avoid cephalosporins altogether given anaphylactic PCN history","Give a test dose of nafcillin","No precautions are needed"], correct:1, explain:"Cross-reactivity risk is low (1–4%) but anaphylactic PCN history means cephalosporins should be avoided.", torture:false},

  // ---------------- Cell Wall Agents ----------------
  {topic:"cellwall", q:"What is the shared mechanism of action for penicillins, cephalosporins, and carbapenems?", options:["Inhibit protein synthesis","Inhibit cell wall synthesis","Inhibit DNA synthesis","Inhibit folic acid synthesis"], correct:1, explain:"All beta-lactams inhibit bacterial cell wall (peptidoglycan) synthesis via transpeptidase inhibition.", torture:false},
  {topic:"cellwall", q:"Which drug is the classic choice for surgical prophylaxis?", options:["Ceftriaxone","Cefazolin (1st generation cephalosporin)","Nafcillin","Meropenem"], correct:1, explain:"Cefazolin (1st gen) is IV-only and the standard for surgical prophylaxis.", torture:false},
  {topic:"cellwall", q:"Which cephalosporin generation crosses the blood-brain barrier and is used for meningitis?", options:["1st generation","2nd generation","3rd generation (e.g., ceftriaxone)","None of them cross the BBB"], correct:2, explain:"Ceftriaxone (3rd gen) is long-acting and crosses the BBB, making it useful for meningitis.", torture:false},
  {topic:"cellwall", q:"A patient on vancomycin develops flushing, rash, and hypotension during a rapid infusion. What is this?", options:["Anaphylaxis — stop the drug permanently","Red Man Syndrome — slow the infusion rate","A sign of nephrotoxicity","Normal, no action needed"], correct:1, explain:"Red Man Syndrome is infusion-rate related, not a true allergy. Slow the infusion.", torture:false},
  {topic:"cellwall", q:"Which route of vancomycin is used specifically to treat C. difficile colitis?", options:["IV","IM","Oral","Topical"], correct:2, explain:"Oral vancomycin stays in the GI tract, which is exactly where it's needed for C. diff.", torture:false},
  {topic:"cellwall", q:"What is the biggest adverse effect to monitor for with carbapenems?", options:["Tendon rupture","Seizure activity","Tooth discoloration","QT prolongation"], correct:1, explain:"Carbapenems carry a seizure risk, especially in elderly patients or those on other seizure-threshold-lowering meds.", torture:false},
  {topic:"cellwall", q:"Piperacillin-tazobactam is always given with a beta-lactamase inhibitor. Why?", options:["To improve taste","To protect the drug from being broken down by bacterial beta-lactamase","To reduce IV volume","To shorten infusion time"], correct:1, explain:"Beta-lactamase inhibitors (like tazobactam) protect the beta-lactam ring from bacterial enzymes that would otherwise inactivate it.", torture:false},

  // ---------------- Protein/DNA/Folate Synthesis Inhibitors ----------------
  {topic:"protein", q:"Which adverse effect of aminoglycosides is usually PERMANENT?", options:["Nephrotoxicity","Ototoxicity","Rash","Photosensitivity"], correct:1, explain:"Nephrotoxicity is usually reversible; ototoxicity is usually permanent.", torture:false},
  {topic:"protein", q:"Which drug carries the highest risk of causing pseudomembranous colitis?", options:["Azithromycin","Clindamycin","Doxycycline","Ciprofloxacin"], correct:1, explain:"Clindamycin is specifically flagged for its risk of causing deadly pseudomembranous colitis.", torture:false},
  {topic:"protein", q:"A patient is prescribed azithromycin. What teaching point applies?", options:["Take with a large fatty meal","Take without food, since food decreases absorption","Take only at bedtime","Avoid all dairy products"], correct:1, explain:"Food decreases azithromycin absorption; it's best taken without food.", torture:false},
  {topic:"protein", q:"Tetracyclines are contraindicated in which patient?", options:["A 45-year-old with a UTI","A 6-year-old child","An adult with a penicillin allergy","An elderly patient with hypertension"], correct:1, explain:"Tetracyclines cause permanent tooth discoloration and enamel hypoplasia in children under 8 and in pregnancy.", torture:false},
  {topic:"protein", q:"Which class works by altering bacterial DNA via DNA gyrase/topoisomerase inhibition?", options:["Macrolides","Fluoroquinolones","Tetracyclines","Aminoglycosides"], correct:1, explain:"Fluoroquinolones (cipro, levofloxacin) interfere with DNA gyrase and topoisomerase.", torture:false},
  {topic:"protein", q:"Ciprofloxacin should generally be avoided in which age groups due to arthropathy risk?", options:["Under 18 and over 60","Under 5 and over 80","Only pregnant patients","There is no age restriction"], correct:0, explain:"Fluoroquinolones carry a risk of often-irreversible joint/tendon damage — avoid under 18 and over 60 when possible.", torture:false},
  {topic:"protein", q:"What critical teaching point goes with metronidazole (Flagyl)?", options:["Take with alcohol to improve absorption","Never take with alcohol","Must be taken on an empty stomach only","Avoid all antibiotics while on this drug"], correct:1, explain:"Metronidazole + alcohol can cause a severe disulfiram-like reaction.", torture:false},

  // ---------------- Antivirals ----------------
  {topic:"antivirals", q:"Why are there relatively few antiviral drugs compared to antibacterials?", options:["Viruses are too small to target","Viruses replicate inside host cells, so killing the virus risks killing the host cell","Antivirals are too expensive to develop","There is no market need for antivirals"], correct:1, explain:"Because viruses live inside host cells, drugs strong enough to kill them can also harm healthy host cells.", torture:false},
  {topic:"antivirals", q:"Acyclovir is used to manage which condition?", options:["Cures HSV/VZV permanently","Suppresses HSV/VZV replication and reduces outbreak severity, but is not a cure","Treats influenza A","Treats CMV in transplant patients"], correct:1, explain:"Acyclovir suppresses but does not cure herpes family viruses; outbreaks can still recur.", torture:false},
  {topic:"antivirals", q:"Oseltamivir (Tamiflu) is most effective when started within how many hours of flu symptom onset?", options:["12 hours","48 hours","1 week","It has no time restriction"], correct:1, explain:"Oseltamivir works best when started within 48 hours of symptom onset.", torture:false},
  {topic:"antivirals", q:"Which drug carries black box warnings for hematologic toxicity and fetal toxicity, and treats CMV?", options:["Acyclovir","Ganciclovir","Oseltamivir","Valacyclovir"], correct:1, explain:"Ganciclovir treats CMV in immunocompromised patients but carries serious black box warnings.", torture:false},

  // ---------------- HIV ----------------
  {topic:"hiv", q:"Which enzyme does HIV use to convert its RNA into DNA?", options:["Protease","Integrase","Reverse transcriptase","Neuraminidase"], correct:2, explain:"Reverse transcriptase is the defining enzyme of a retrovirus, converting RNA into DNA.", torture:false},
  {topic:"hiv", q:"A diagnosis of AIDS requires which of the following?", options:["CD4 count under 500 only","An AIDS-defining condition OR CD4 count under 200 cells/mm³","A positive viral load test only","Symptoms lasting more than 10 years"], correct:1, explain:"AIDS is diagnosed by an AIDS-defining illness OR a CD4 count under 200, regardless of symptoms.", torture:false},
  {topic:"hiv", q:"What is the goal of antiretroviral therapy (ART)?", options:["Cure the infection completely","Decrease viral load to an undetectable level","Increase viral load to boost immunity","Eliminate the need for CD4 monitoring"], correct:1, explain:"ART aims to suppress viral load to undetectable levels, allowing CD4 recovery — it does not cure HIV.", torture:false},
  {topic:"hiv", q:"What is the black box warning associated with NRTIs?", options:["Lactic acidosis syndrome","QT prolongation","Tendon rupture","Tooth discoloration"], correct:0, explain:"NRTIs carry a black box warning for lactic acidosis syndrome; lactate is monitored early in treatment.", torture:false},
  {topic:"hiv", q:"A healthcare worker in a stable relationship with an HIV-positive partner wants to reduce their own risk before any exposure. What is this called?", options:["PEP (post-exposure prophylaxis)","PrEP (pre-exposure prophylaxis)","ART (antiretroviral therapy)","Prophylactic antibiotic use"], correct:1, explain:"PrEP is taken before exposure and can reduce transmission risk by more than 90%.", torture:false},
  {topic:"hiv", q:"After a needle-stick exposure to an HIV-positive source, PEP is typically given for how long, with testing at what intervals?", options:["7 days; tested at 2 and 4 weeks","28 days; tested at 6 and 12 weeks","90 days; tested at 3 and 6 months","PEP is not given after needle-stick exposure"], correct:1, explain:"PEP is a 28-day ART course, with HIV testing at 6 and 12 weeks post-exposure.", torture:false},

  // ---------------- TORTURE CHAMBER (trickiest / easily mixed up) ----------------
  {topic:"cellwall", torture:true, q:"A patient allergic to sulfa drugs is prescribed piperacillin-tazobactam. Is this a concern?", options:["Yes — tazobactam is a sulfa-containing compound", "No — beta-lactamase inhibitors like tazobactam are not sulfonamides, and this is a different allergy category entirely","Yes, because all extended-spectrum penicillins contain sulfa","No, because sulfa allergy only matters for cephalosporins"], correct:1, explain:"Sulfa allergy relates to sulfonamide antibiotics (e.g., Bactrim), not beta-lactam/beta-lactamase-inhibitor combinations — these are unrelated allergy categories, a classic exam trap."},
  {topic:"protein", torture:true, q:"Both aminoglycosides and vancomycin require peak/trough monitoring and carry nephrotoxicity/ototoxicity risk. What key mechanism difference separates them?", options:["Aminoglycosides inhibit protein synthesis; vancomycin inhibits cell wall synthesis","They work by the exact same mechanism","Vancomycin inhibits protein synthesis; aminoglycosides inhibit cell wall synthesis","Neither affects bacterial structure"], correct:0, explain:"Despite similar toxicity monitoring, aminoglycosides target the ribosome (protein synthesis) while vancomycin targets the cell wall — a common source of exam confusion."},
  {topic:"cellwall", torture:true, q:"A patient with an anaphylactic penicillin allergy needs a serious gram-negative infection treated. Which class is safest to avoid entirely due to cross-reactivity risk?", options:["Fluoroquinolones","Cephalosporins","Macrolides","Tetracyclines"], correct:1, explain:"Cephalosporins share the beta-lactam ring structure with penicillins — avoid entirely if the penicillin reaction was anaphylactic, even though overall cross-reactivity is only 1–4%."},
  {topic:"principles", torture:true, q:"A patient has diarrhea while taking amoxicillin. Is this an allergic reaction requiring the drug be stopped and documented as an allergy?", options:["Yes, always stop and document a permanent allergy","No — diarrhea is a known adverse effect of aminopenicillins, not a true allergy","Yes, but only if it happens twice","No, but the patient should be switched to a stronger antibiotic immediately"], correct:1, explain:"Diarrhea and rash are well-documented common adverse effects of ampicillin/amoxicillin — not the same as a true allergic reaction (hives, angioedema, anaphylaxis)."},
  {topic:"protein", torture:true, q:"Both tetracyclines and fluoroquinolones are broad-spectrum and bacteriostatic/bactericidal respectively — but which one is specifically contraindicated in children under 8 due to permanent tooth staining?", options:["Fluoroquinolones","Tetracyclines","Both equally","Neither — this applies to macrolides"], correct:1, explain:"Tooth discoloration/enamel hypoplasia is a tetracycline-specific effect; fluoroquinolones instead carry an age-related tendon/joint risk (avoid under 18 and over 60) — easy to mix up on an exam."},
  {topic:"hiv", torture:true, q:"A patient's HIV viral load is undetectable on ART. What is still true about their HIV status and transmission risk?", options:["They are cured and no longer HIV-positive","They are still HIV-positive, but transmission risk is effectively eliminated at an undetectable viral load","They are still highly infectious despite treatment","Undetectable viral load only applies to CD4 count, not transmission"], correct:1, explain:"Undetectable = effectively untransmittable, but the person remains HIV-positive for life — ART controls, it does not cure."},
  {topic:"cellwall", torture:true, q:"Ceftriaxone and cefepime both cross the blood-brain barrier. Which one should be avoided in patients with liver failure?", options:["Cefepime","Ceftriaxone","Both should be avoided in liver failure","Neither is affected by liver function"], correct:1, explain:"Ceftriaxone specifically should be avoided in liver failure — a detail that's easy to confuse with cefepime, its 4th-generation cousin."},
  {topic:"principles", torture:true, q:"MIC and MBC sound similar. Which statement correctly distinguishes them?", options:["MIC kills 99.9% of organisms; MBC only inhibits growth","MIC is the lowest concentration that inhibits growth; MBC is the lowest concentration that kills ≥99.9% of the colony","They are interchangeable terms for the same lab value","MBC is always a lower concentration than MIC"], correct:1, explain:"MIC = inhibits growth (doesn't necessarily kill). MBC = actually kills the organism (≥99.9% reduction). MBC is typically equal to or higher than MIC."},

  // ---------------- From Sherpath EAQ Study Guide (Lilley, 10th ed. — Ch. 38–40) ----------------
  {topic:"antivirals", q:"The nurse observes cold sores around a patient's mouth. Which virus would have caused this?", options:["Herpes simplex type 1","Epstein-Barr virus (EBV)","Cytomegalovirus (CMV)","Varicella-zoster virus (VZV)"], correct:0, explain:"HSV-1 causes mucocutaneous infections around the oral cavity (cold sores/fever blisters). EBV causes mono; CMV causes opportunistic/retinitis infection; VZV causes chickenpox/shingles.", torture:false, source:"EAQ"},
  {topic:"principles", q:"Which condition occurs when normal flora are disturbed during antibiotic therapy?", options:["Organ toxicity","Superinfection","Hypersensitivity","Rebound toxicity"], correct:1, explain:"A superinfection develops when antibiotic therapy disrupts normal protective flora, letting opportunistic organisms like C. diff or Candida overgrow.", torture:false, source:"EAQ"},
  {topic:"cellwall", q:"Which mechanism describes how penicillin destroys bacteria?", options:["It interferes with cell wall synthesis","It binds irreversibly to the cell wall","It interrupts bacterial DNA processes","It interrupts bacterial RNA processes"], correct:0, explain:"Penicillins bind penicillin-binding proteins, inhibiting transpeptidation needed for peptidoglycan (cell wall) synthesis, causing osmotic lysis.", torture:false, source:"EAQ"},
  {topic:"principles", q:"Which lab value is measured to assess a patient's renal function before starting antibiotic therapy?", options:["ALT","Serum creatinine","Troponin","Serum calcium"], correct:1, explain:"Serum creatinine (with BUN/eGFR) evaluates renal function — essential since many antimicrobials are renally eliminated and nephrotoxic.", torture:false, source:"EAQ"},
  {topic:"antivirals", q:"Which microorganism is directly treated by acyclovir?", options:["Herpes zoster", "Proteus vulgaris", "Pneumocystis carinii", "Staphylococcus aureus"], correct:0, explain:"Acyclovir treats herpesviruses (HSV-1, HSV-2, VZV/herpes zoster) — not bacteria or Pneumocystis.", torture:false, source:"EAQ"},
  {topic:"protein", torture:true, q:"A patient takes a calcium supplement within an hour of a dose of levofloxacin. What happens?", options:["Impaired levofloxacin absorption", "Increased serum concentration of levofloxacin", "Reduced antibacterial activity with normal absorption", "Altered intestinal flora"], correct:0, explain:"Divalent/trivalent cations (calcium, magnesium, aluminum, iron) chelate with fluoroquinolones in the GI tract, forming an insoluble complex that severely impairs absorption. Space these at least 2 hours apart.", source:"EAQ"},
  {topic:"principles", q:"A patient receives IV ceftriaxone before an open cholecystectomy. What type of antibiotic therapy is this?", options:["Empiric", "Definitive", "Prophylactic", "Colonization"], correct:2, explain:"Prophylactic therapy is given before a procedure to prevent surgical site/systemic infection — distinct from empiric (started before culture results) or definitive (targeted to a known pathogen) therapy.", torture:false, source:"EAQ"},
  {topic:"protein", q:"A patient is on both vancomycin and tobramycin. Which lab should the nurse prioritize monitoring?", options:["Serum glucose", "Serum creatinine", "Prothrombin time", "Serum electrolytes"], correct:1, explain:"Vancomycin and tobramycin both carry nephrotoxicity/ototoxicity risk — combined use is additive. Monitor serum creatinine, BUN, and trough levels closely.", torture:false, source:"EAQ"},
  {topic:"protein", q:"What is the correct instruction for applying topical clindamycin?", options:["Squeeze the tube directly into the vagina", "Refrigerate the reconstituted medication between uses", "Cleanse the skin with an exfoliating agent first", "Apply a thin layer to the affected area after it has been cleansed"], correct:3, explain:"Topical clindamycin should be applied as a thin layer to clean, dry skin — avoid exfoliants/harsh soaps, which add irritation. Vaginal forms use a measured applicator, not this technique.", torture:false, source:"EAQ"},
  {topic:"protein", q:"Which foods should a patient avoid while taking levofloxacin?", options:["Sugary foods", "Dairy products", "Fiber-rich foods", "Protein-rich foods"], correct:1, explain:"Dairy and calcium-fortified juices chelate with fluoroquinolones, impairing GI absorption — space dairy at least 2 hours from the dose.", torture:false, source:"EAQ"},
  {topic:"principles", q:"A patient reports flushing, itching, hives, anxiety, and throat/tongue swelling after an antibiotic dose. What is this?", options:["Tolerance to the antibiotic", "An allergic anaphylactic reaction", "A C. diff infection", "G6PD deficiency"], correct:1, explain:"Flushing, urticaria, anxiety, and angioedema of the throat/tongue are hallmark signs of type I IgE-mediated anaphylaxis — a medical emergency requiring immediate intervention.", torture:false, source:"EAQ"},
  {topic:"cellwall", torture:true, q:"Which medication is added to ampicillin specifically to enhance its effectiveness against beta-lactamase–producing bacteria?", options:["Calcium citrate", "Clavulanic acid", "Acetaminophen", "Carbamazepine"], correct:1, explain:"Clavulanic acid (like sulbactam/tazobactam) is a beta-lactamase inhibitor that protects the beta-lactam ring from enzymatic breakdown, broadening antimicrobial coverage.", source:"EAQ"},
  {topic:"principles", q:"What should a patient be taught about a possible allergic reaction to an antibacterial drug?", options:["Allergic reactions always show as urticaria or pruritus", "An allergic reaction will only occur after the first dose", "Any adverse effect is considered an allergic reaction", "Stop the medication immediately at the first sign of an allergic reaction"], correct:3, explain:"Patients should discontinue the drug and contact their prescriber at the earliest sign of hypersensitivity to prevent progression to anaphylaxis. Reactions often occur after multiple doses, not just the first.", torture:false, source:"EAQ"},
  {topic:"protein", torture:true, q:"A patient on tobramycin has a serum trough concentration greater than 2 mcg/mL. Which adverse effect should the nurse monitor for?", options:["Heartburn", "Hearing impairment", "Metallic taste", "Red man syndrome"], correct:1, explain:"Elevated aminoglycoside trough levels raise concentration-dependent ototoxicity risk (hearing loss, tinnitus, dizziness) and nephrotoxicity. Red man syndrome is specific to vancomycin, not tobramycin.", source:"EAQ"},
  {topic:"antivirals", q:"Which agent treats most infections caused by herpes simplex virus and varicella-zoster virus?", options:["Acyclovir", "Zanamivir", "Ganciclovir", "Amantadine"], correct:0, explain:"Acyclovir is first-line for HSV-1, HSV-2, and VZV. Zanamivir treats influenza, ganciclovir treats CMV, and amantadine targets influenza A.", torture:false, source:"EAQ"},
  {topic:"protein", torture:true, q:"What is the principal indication for sulfamethoxazole-trimethoprim (Bactrim)?", options:["Meningeal infection", "Bacterial pneumonia", "Bacterial endocarditis", "Urinary tract infection"], correct:3, explain:"Sulfonamides concentrate heavily in renal tissue/urine, making Bactrim primarily indicated for susceptible UTIs (commonly E. coli) rather than meningitis, pneumonia, or endocarditis.", source:"EAQ"},
  {topic:"antivirals", q:"A patient is diagnosed with genital herpes. Which drug is used to treat and manage this infection?", options:["Ribavirin", "Acyclovir", "Zidovudine", "Amantadine"], correct:1, explain:"Acyclovir (or its prodrug valacyclovir) is the drug of choice for initial and recurrent genital herpes (HSV-2/HSV-1). Ribavirin treats RSV/HCV, zidovudine is an HIV antiretroviral, and amantadine treats influenza A.", torture:false, source:"EAQ"},
  {topic:"antivirals", q:"A nurse is administering IV acyclovir. What is essential for safe administration?", options:["Monitor the IV site closely", "Avoid diluting the drug", "Limit fluid intake during therapy", "Administer as an IV push"], correct:0, explain:"IV acyclovir is a significant venous irritant that can cause chemical phlebitis and tissue damage with extravasation — monitor the site closely. It must be diluted, infused slowly over at least 1 hour (never IV push), with generous hydration to prevent renal crystallization.", torture:false, source:"EAQ"},
  {topic:"antivirals", q:"Which routes of administration are appropriate for ribavirin?", options:["IV and IM only", "Subcutaneous only", "Inhalation and oral", "Topical only"], correct:2, explain:"Ribavirin is given by aerosol inhalation (Virazole, via SPAG-2 generator) for severe pediatric RSV, and orally in combination therapy for chronic hepatitis C. It is not given IM, SubQ, or standard IV.", torture:false, source:"EAQ"},
];
